baseURL = "http://cantaverde.github.io/"
title = "Chorale Canta Verde"

DefaultContentLanguage = "fr"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1

    [languages.fr.blackfriday]
      angledQuotes = true

